TOP = ..
include $(TOP)/configure/CONFIG
DIRS += Db
DIRS += opi
DIRS += pmacAsynIPPortSrc
DIRS += pmacAsynMotorPortSrc
DIRS += pmacAsynMotorSrc
DIRS += src
DIRS += src_eth
DIRS += tsubSrc
include $(TOP)/configure/RULES_DIRS
