TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this

DB += ../softDb/AssyGeneric.db
DB += ../softDb/Load05X3.db
DB += ../softDb/Load08XY3.db
DB += ../softDb/Load08XY3_mono.db
DB += ../softDb/MotionPrg.db
DB += ../pmacDb/Ram05X3.db
DB += ../pmacDb/Ram08XY3.db
DB += ../moDb_2mtr_cry2down/MO_Calibrate.db
DB += ../moDb_2mtr_cry2down/MO_LimAmp.db
DB += ../moDb_2mtr_cry2down/MO_TsubRqsPos.db
DB += ../moDb_2mtr_cry2down/MO_TsubRqsBkl.db
DB += ../moDb_2mtr_cry2down/MO_TsubRbk.db
DB += ../moDb_2mtr_cry2down/MO_TsubSpeed.db
DB += ../pmacDb/AsciiMtr.db
DB += ../pmacDb/IxMtrMv.db
DB += ../pmacDb/OpnLp.db
DB += ../softDb/LimTransfer.db
DB += ../pmacDb/mtrdat.db
DB += ../pmacDb/mtrdat_out.db
DB += ../softDb/RqsTwkMem.db
DB += ../pmacDb/AsciiPcs.db
DB += ../pmacDb/bkgfix1pcs.db
DB += ../pmacDb/CtlPnlPcs.db
DB += ../pmacDb/Acc59E.db
DB += ../pmacDb/AsciiPmac.db
DB += ../pmacDb/bkgfix0.db
DB += ../pmacDb/bkgvar0.db
DB += ../pmacDb/CtlPnlPmac.db
DB += ../pmacDb/mbxvar0.db
DB += ../pmacDb/svofix0.db
DB += ../xDb/X_Calibrate.db
DB += ../xDb/X_LimAmp.db
DB += ../xDb/X_Tsub.db
DB += ../xDb/X_TsubRbk.db
DB += ../xDb/X_TsubSpeed.db
DB += ../xyDb/XY_Calibrate.db
DB += ../xyDb/XY_LimAmp.db
DB += ../xyDb/XY_Tsub.db
DB += ../xyDb/XY_TsubRbk.db
DB += ../xyDb/XY_TsubSpeed.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>
#USES_TEMPLATE += ao_XY542.db
#USES_TEMPLATE += ai_XY542.db
#USES_TEMPLATE += v_motor.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
