TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += keithley.db
#DB += ai_IK342.db
#DB += ao_XY542.db
#DB += ai_XY542.db
#DB += XY542.substitutions
#DB += virt_motor.substitutions

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>
#USES_TEMPLATE += ao_XY542.db
#USES_TEMPLATE += ai_XY542.db
#USES_TEMPLATE += v_motor.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

