TOP=../..

include $(TOP)/configure/CONFIG

# -------------------------------

DBD += pmacAsynMotorPort.dbd

LIBRARY = pmacAsynMotorPort
pmacAsynMotorPort_SRCS = pmacController.cpp pmacAxis.cpp

include $(TOP)/configure/RULES
