TOP=../..

include $(TOP)/configure/CONFIG

# -------------------------------

DBD = pmacAsynCoord.dbd

LIBRARY = pmacAsynCoord
pmacAsynCoord_SRCS = pmacAsynCoord.c pmacAsynCoordRegister.cc

include $(TOP)/configure/RULES
