TOP=../..

include $(TOP)/configure/CONFIG

# -------------------------------

DBD = pmacAsynMotor.dbd

LIBRARY = pmacAsynMotor
pmacAsynMotor_SRCS = pmacAsynMotor.c pmacAsynMotorRegister.cc

include $(TOP)/configure/RULES
